// municipiosRepartos.js
const municipiosRepartos = {
	'Habana Vieja': ['Prado', 'Santo Ángel', 'Catedral', 'Plaza Vieja', 'Belén', 'Jesús María', 'San Isidro', 'Tallapiedra'],
	'Centro Habana': ['Cayo Hueso', 'Dragones', 'Colón', 'Pueblo Nuevo', 'Los Sitios', 'Barrio Chino'],
	'Cerro': ['Casino Deportivo', 'Martí', 'Palatino', 'Santa Catalina', 'Villanueva', 'Ayestarán', 'Pilar', 'Atares'],
	'10 de Octubre': ['A ambos lados de la calzada de 10 de octubre', 'antigua Jesús del Monte'],
	'Plaza': ['Vedado', 'Miramar', 'Siboney', 'Alturas de Almendares', 'Kohly'],
	'Arroyo Naranjo': ['Los Pinos', 'Mantilla', 'Calabazar', 'Wajay', 'Santiago de las Vegas', 'Eléctrico'],
	'Boyeros': ['Alamar', 'Santiago de las Vegas', 'Eléctrico', 'Calabazar', 'Wajay', 'Las Cañas'],
	'Cotorro': ['Santa María del Rosario', 'Güira de Melena', 'Jaruco', 'Madruga', 'San José de las Lajas'],
	'San Miguel del Padrón': [
		'Camilo Cienfuegos',
		'Diezmero',
		'Eléctrico',
		'Guanabacoa',
		'La Ceiba',
		'Luyanó Moderno',
		'Luyanó',
		'Mariano',
		'Párraga',
		'Pogolotti',
		'Sevillano',
		'Víbora Park',
		'Zamora',
	],
	'Playa': ['Miramar', 'Siboney', 'Flores', 'La Sierra', 'Santa Fe', 'Cubanacán', 'Kohly', 'Náutico', 'Nuevo Vedado', 'Almendares'],
	'Marianao': [
		'La Lisa',
		'Pogolotti',
		'Sevillano',
		'Luyanó Moderno',
		'Luyanó',
		'Mariano',
		'Párraga',
		'Víbora Park',
		'Zamora',
		'Cubanacán',
		'Kohly',
		'Náutico',
		'Nuevo Vedado',
		'Almendares',
	],
	'La Lisa': [
		'Punta Brava',
		'La Palma',
		'La Ceiba',
		'La Fortuna',
		'San Agustín',
		'San Pedro',
		'Santa Felicia',
		'Santa Fe',
		'Santa Teresa',
		'San Antonio',
		'San José',
		'San Miguel',
		'San Nicolás',
		'San Pedro',
		'San Rafael',
		'San Ramón',
		'San Ricardo',
		'San Roque',
		'San Vicente',
		'Santa Ana',
		'Santa Bárbara',
		'Santa Clara',
		'Santa Cruz',
		'Santa Emilia',
		'Santa Isabel',
		'Santa Lucía',
		'Santa María',
		'Santa Marta',
		'Santa Rosa',
		'Santa Teresa',
		'Santa Teresita',
	],
};

export default municipiosRepartos;
